version: '3'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - "DB_HOST=postgres"
      - "REDIS_HOST=redis"
    restart: on-failure

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest