service: cyber-auth
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  stage: dev
  region: eu-central-1
  timeout: 15
  environment:
    HASH_SALT: ${env:HASH_SALT}
    LOGGING: ${env:LOGGING}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    JWT_SECRET: ${env:JWT_SECRET}
    PORT: ${env:PORT}

functions:
  hello:
    handler: src/serverless.handler
    timeout: 30
    events:
      - http: 
          path: /{proxy+}
          method: any

    
